### ISSUE TITLE
How final is the API?

### ISSUE THREAD

**Issue by jeffreybiles** [lifegadget/ui-navigator-service#1]
This looks awesome.  I'd love to make a screencast about it.  Do you plan on making significant changes from here on out or is it safe to screencast on?

**Comment by yankeeinlondon** [comment]
I don't expect the external API to change much (only additive if at all). Internally there may come a time when my method for discovering the Application controller has to change but that shouldn't effect users.

**Comment by yankeeinlondon** [comment]
I'm in fact using this in several other apps already and it was just time for me to pull it out the various apps and make it its own thing :)

**Comment by jeffreybiles** [comment]
Excellent, thank you :D

**Comment by jeffreybiles** [comment]
I'm closing this since I made the video :)

Check out the PR: https://github.com/lifegadget/ui-navigator-service/pull/2

**Comment by yankeeinlondon** [comment]
;)

Been overloaded this week but looking forward to watching it this weekend.

**Comment by jeffreybiles** [comment]
Awesome.  Happy Thanksgiving!
