### ISSUE TITLE
Ember 2.x has `container` deprecations

### ISSUE THREAD

**Issue by lancedikson** [lifegadget/ui-navigator-service#3]
Running navigator-service with Ember 2.x shows the deprecation:

```
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
```

Don't forget to fix it before the next Ember major version update, please.
And thank you for the service :+1:

**Comment by yankeeinlondon** [comment]
Been quite heads down these past two weeks. Interesting error, haven't seen it yet myself but I'll go looking for it tomorrow.

**Comment by yankeeinlondon** [comment]
Ok, have released it under `0.2.0`. I'll mark it closed but feel free to reopen if you have any issues with it. 

> note: i also decided to include some default injections into routes, components, and views (just an FYI, it's in the README now)

**Comment by FernandaS** [comment]
@lancedikson how did you fix that deprecation? I am getting the same thing
`DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.`

**Comment by yankeeinlondon** [comment]
https://github.com/lifegadget/ui-navigator-service/blob/012400dfebb59f101f2179c1482d7cb88279dac9/addon/services/navigator.js#L2-L10

**Comment by FernandaS** [comment]
thanks @ksnyde
