### ISSUE TITLE
Service not working in component

### ISSUE THREAD

**Issue by therealbenhogan** [lifegadget/ui-navigator-service#5]
Hi, 

I am trying the service within a component - can get information about the current route, but not the dynamic segment; is this possible? I want to give a page an active class and for a lot of  the pages that will require obtaining the info about the last part of the url, the dynamic segment.

**Comment by lancedikson** [comment]
@therealbenhogan, looks like `navigator` can't do that for you. But if you'll find graceful solution to do that you can try to propose it here to implement.

**Comment by yankeeinlondon** [comment]
If I understand what you're trying to do this should be possible. Can you give me a little more detail on what you're getting blocked on?

**Comment by therealbenhogan** [comment]
Hi, 

Many thanks for getting back. I was trying to use the plugin to obtain the value of the dynamic segment of a url (in my case the last part) because I was trying to use the ember-href-to plugin rather than the standard Link Component for my navigation. By knowing the value of the dynamic segment I could mark an element in a nav bar (for example) as active and then do the same for all of its parents. 

A segment of my router would look like 

```
 this.route('product.categories',{path:'/product/categories/:slug'});
```

I thought I would be able to obtain the information I wanted from your routeParts computed property.

Hope that helps?

**Comment by yankeeinlondon** [comment]
Check out `0.3.0`, I've added some parameters to help. It still can't automatically detect when you maintain the same route but change the dynamic segments but if you need this just have your nav bar call the new navigator.refresh() method and that will force the dynamic segments to update.

> Note: they do dynamically update when you change _routes_ it's only when you have a static route but change segment parameters. I tried creating dynamic observers but couldn't get that to work and I suspect the `refresh()` method will suffice for most use-cases.

**Comment by therealbenhogan** [comment]
Many thanks - will take a look
